version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      next:
        patterns: ["next", "react", "react-dom"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
