"""Demo reference data.

REFERENCE_EVENTS is the resolved-event corpus the Quant Agent matches new
questions against. SEED_QUESTIONS are live demo questions with their market
state and evidence snapshots. In production these would be fed by ingest
pipelines (prediction markets, news APIs, SEC filings, arXiv, social).
"""

# (question text, category, outcome) — 1 resolved YES, 0 resolved NO
REFERENCE_EVENTS: list[tuple[str, str, int]] = [
    ("Will the Federal Reserve cut interest rates at the March meeting?", "finance", 0),
    ("Will the Federal Reserve cut interest rates in the second half of the year?", "finance", 1),
    ("Will the Fed hold rates steady through the summer?", "finance", 1),
    ("Will US CPI inflation fall below 3% by year end?", "finance", 1),
    ("Will NVIDIA beat quarterly earnings estimates?", "finance", 1),
    ("Will NVIDIA beat earnings estimates for a sixth straight quarter?", "finance", 1),
    ("Will Apple beat quarterly revenue estimates?", "finance", 1),
    ("Will Tesla beat quarterly delivery estimates?", "finance", 0),
    ("Will the S&P 500 close the year above its January level?", "finance", 1),
    ("Will a major US bank fail this year?", "finance", 0),
    ("Will Stripe IPO this year?", "finance", 0),
    ("Will a top-5 AI lab IPO this year?", "finance", 0),
    ("Will OpenAI release a new frontier model this year?", "technology", 1),
    ("Will OpenAI release GPT-5 before the end of the year?", "technology", 1),
    ("Will Anthropic release a new frontier Claude model this year?", "technology", 1),
    ("Will Google release a new Gemini flagship model this year?", "technology", 1),
    ("Will Apple announce a foldable iPhone this year?", "technology", 0),
    ("Will a new AI chip startup reach a $10B valuation this year?", "technology", 1),
    ("Will global semiconductor sales grow year over year?", "technology", 1),
    ("Will an AI chip shortage constrain data center buildouts this year?", "technology", 1),
    ("Will a self-driving robotaxi service launch in a new major US city this year?", "technology", 1),
    ("Will a humanoid robot be deployed commercially at scale this year?", "technology", 0),
    ("Will Bitcoin reach a new all-time high this year?", "crypto", 1),
    ("Will Bitcoin double in price this year?", "crypto", 0),
    ("Will Ethereum flip Bitcoin by market cap this year?", "crypto", 0),
    ("Will a US spot crypto ETF see net inflows this quarter?", "crypto", 1),
    ("Will the incumbent party win the presidential election?", "politics", 0),
    ("Will a government shutdown occur this fiscal year?", "politics", 0),
    ("Will a major tariff package be enacted this year?", "politics", 1),
    ("Will a new Supreme Court justice be confirmed this year?", "politics", 0),
    ("Will a ceasefire agreement be signed in the major ongoing conflict this year?", "politics", 0),
    ("Will a room-temperature superconductor be replicated this year?", "science", 0),
    ("Will a CRISPR-based therapy receive a new FDA approval this year?", "science", 1),
    ("Will a fusion experiment achieve net energy gain again this year?", "science", 1),
    ("Will a new heaviest element be confirmed this year?", "science", 0),
    ("Will SpaceX complete a fully successful Starship orbital flight this year?", "science", 1),
    ("Will the favorite win the NBA championship?", "sports", 0),
    ("Will the favorite win the Super Bowl?", "sports", 1),
    ("Will a Grand Slam singles title go to a first-time winner this year?", "sports", 1),
    ("Will the transfer-window spending record be broken this year?", "sports", 0),
]

# Live demo questions: (question, category, horizon_days, market_probability,
#   volume_usd, liquidity, evidence[])
# evidence: (source, summary, sentiment, impact)
SEED_QUESTIONS: list[dict] = [
    {
        "question": "Will the Federal Reserve cut interest rates before the December meeting?",
        "category": "finance",
        "horizon_days": 120,
        "market_probability": 0.62,
        "volume_usd": 4_800_000,
        "liquidity": "high",
        "evidence": [
            ("FOMC minutes", "Minutes show a growing bloc of members favoring earlier easing.", "positive", 0.8),
            ("CPI print", "Core inflation came in below consensus for the second straight month.", "positive", 0.7),
            ("Labor market", "Payroll growth slowed but unemployment remains near cycle lows.", "positive", 0.5),
            ("Fed speeches", "Two regional presidents pushed back publicly on near-term cuts.", "negative", 0.6),
            ("Energy prices", "Oil rally threatens a re-acceleration of headline inflation.", "negative", 0.5),
        ],
    },
    {
        "question": "Will NVIDIA beat consensus earnings estimates next quarter?",
        "category": "finance",
        "horizon_days": 60,
        "market_probability": 0.72,
        "volume_usd": 2_100_000,
        "liquidity": "high",
        "evidence": [
            ("Supply chain", "Blackwell-class GPU demand continues to outrun supply.", "positive", 0.9),
            ("Hyperscaler capex", "All four major hyperscalers raised data center capex guidance.", "positive", 0.8),
            ("Analyst revisions", "Consensus EPS revised up 11% over the past 90 days.", "positive", 0.6),
            ("Export controls", "New export restrictions cloud a mid-single-digit revenue share.", "negative", 0.6),
            ("Margins", "Mix shift toward systems is compressing gross margin sequentially.", "negative", 0.4),
        ],
    },
    {
        "question": "Will OpenAI release GPT-6 before the end of 2027?",
        "category": "technology",
        "horizon_days": 500,
        "market_probability": 0.45,
        "volume_usd": 900_000,
        "liquidity": "medium",
        "evidence": [
            ("Release cadence", "Frontier model generations have shipped roughly every 18-24 months.", "positive", 0.7),
            ("Compute buildout", "Multi-gigawatt training clusters are under construction.", "positive", 0.6),
            ("Hiring signals", "Pretraining team postings reference next-generation model work.", "positive", 0.4),
            ("Naming risk", "The flagship line may be rebranded, resolving the question NO on a technicality.", "negative", 0.5),
            ("Safety reviews", "Longer internal evaluation cycles have delayed recent launches.", "negative", 0.4),
        ],
    },
    {
        "question": "Will Bitcoin trade above $150,000 before the end of the year?",
        "category": "crypto",
        "horizon_days": 140,
        "market_probability": 0.34,
        "volume_usd": 6_500_000,
        "liquidity": "high",
        "evidence": [
            ("ETF flows", "Spot ETF net inflows turned positive after a two-month drawdown.", "positive", 0.6),
            ("Halving cycle", "Post-halving years have historically front-loaded their rallies.", "negative", 0.5),
            ("Macro", "Real yields remain elevated, a historical headwind for BTC.", "negative", 0.6),
            ("Derivatives", "Options skew shows persistent demand for upside strikes.", "positive", 0.4),
        ],
    },
    {
        "question": "Will Tesla launch unsupervised FSD in at least three US states this year?",
        "category": "technology",
        "horizon_days": 150,
        "market_probability": 0.34,
        "volume_usd": 750_000,
        "liquidity": "medium",
        "evidence": [
            ("Robotaxi pilot", "Driverless pilot expanded to a second metro ahead of schedule.", "positive", 0.7),
            ("Regulatory", "Two state DMVs opened frameworks that shortcut permitting.", "positive", 0.6),
            ("Intervention data", "Third-party trackers still show interventions above robotaxi norms.", "negative", 0.7),
            ("Litigation", "Pending NHTSA investigation could force feature rollbacks.", "negative", 0.5),
        ],
    },
    {
        "question": "Will a US government shutdown occur before the end of the fiscal year?",
        "category": "politics",
        "horizon_days": 90,
        "market_probability": 0.28,
        "volume_usd": 1_900_000,
        "liquidity": "high",
        "evidence": [
            ("Appropriations", "Only 4 of 12 appropriations bills have cleared committee.", "positive", 0.6),
            ("Leadership", "Both chambers' leadership publicly committed to a continuing resolution.", "negative", 0.7),
            ("Precedent", "Most shutdown standoffs in the last decade ended in eleventh-hour CRs.", "negative", 0.5),
            ("Faction pressure", "A bloc of holdouts has threatened to block any stopgap.", "positive", 0.5),
        ],
    },
    {
        "question": "Will a CRISPR-based therapy win a new FDA approval within 12 months?",
        "category": "science",
        "horizon_days": 365,
        "market_probability": 0.41,
        "volume_usd": 220_000,
        "liquidity": "low",
        "evidence": [
            ("Pipeline", "Two candidates have PDUFA dates inside the window.", "positive", 0.8),
            ("Precedent", "The first CRISPR approval established a regulatory template.", "positive", 0.6),
            ("Trial risk", "One lead candidate reported a partial clinical hold.", "negative", 0.6),
        ],
    },
    {
        "question": "Will the favorite win the NBA championship this season?",
        "category": "sports",
        "horizon_days": 200,
        "market_probability": 0.31,
        "volume_usd": 3_400_000,
        "liquidity": "high",
        "evidence": [
            ("Roster", "The title favorite returns its full core plus a marquee addition.", "positive", 0.6),
            ("Injury history", "Two of the favorite's stars have missed 20+ games in past seasons.", "negative", 0.6),
            ("Parity", "Pre-season favorites have won only 4 of the last 12 titles.", "negative", 0.7),
        ],
    },
    {
        "question": "Will an AI chip shortage constrain data center buildouts again in 2027?",
        "category": "technology",
        "horizon_days": 400,
        "market_probability": 0.55,
        "volume_usd": 380_000,
        "liquidity": "low",
        "evidence": [
            ("Foundry capacity", "Advanced packaging capacity is sold out through next year.", "positive", 0.8),
            ("Order books", "Hyperscaler GPU orders exceed announced fab expansion plans.", "positive", 0.7),
            ("Supply response", "Three new packaging facilities come online within the window.", "negative", 0.6),
            ("Demand risk", "Any AI capex digestion phase would ease the constraint.", "negative", 0.5),
        ],
    },
    {
        "question": "Will Stripe complete an IPO within 18 months?",
        "category": "finance",
        "horizon_days": 540,
        "market_probability": 0.38,
        "volume_usd": 610_000,
        "liquidity": "medium",
        "evidence": [
            ("Secondary market", "Latest tender valued the company above its prior round.", "positive", 0.5),
            ("Hiring", "Recent CFO-office hires have public-company backgrounds.", "positive", 0.5),
            ("Stated posture", "Leadership has repeatedly said there is no urgency to list.", "negative", 0.7),
            ("Market window", "Fintech IPO comps trade below their last private marks.", "negative", 0.5),
        ],
    },
    {
        "question": "Will SpaceX land Starship's upper stage back at the launch site this year?",
        "category": "science",
        "horizon_days": 160,
        "market_probability": 0.47,
        "volume_usd": 520_000,
        "liquidity": "medium",
        "evidence": [
            ("Test cadence", "Flight test intervals have compressed to under two months.", "positive", 0.7),
            ("Hardware", "Catch-arm hardware for the second tower is complete.", "positive", 0.5),
            ("Regulatory", "Each anomaly investigation has added 1-2 months of delay.", "negative", 0.6),
        ],
    },
    {
        "question": "Will the Fed's preferred inflation gauge fall below 2.5% within 9 months?",
        "category": "finance",
        "horizon_days": 270,
        "market_probability": 0.44,
        "volume_usd": 1_150_000,
        "liquidity": "medium",
        "evidence": [
            ("Trend", "Core PCE has declined for four consecutive quarters.", "positive", 0.7),
            ("Shelter lag", "Rent disinflation is still feeding through with a known lag.", "positive", 0.6),
            ("Tariff pass-through", "New tariffs are expected to add 30-50bps to goods inflation.", "negative", 0.7),
        ],
    },
]
